# Generated by Django 2.0.6 on 2018-06-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180625_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='Image',
            new_name='image',
        ),
    ]
